// Generated by gencpp from file robot1/board.msg
// DO NOT EDIT!


#ifndef ROBOT1_MESSAGE_BOARD_H
#define ROBOT1_MESSAGE_BOARD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot1
{
template <class ContainerAllocator>
struct board_
{
  typedef board_<ContainerAllocator> Type;

  board_()
    : robot_x(0)
    , robot_y(0)  {
    }
  board_(const ContainerAllocator& _alloc)
    : robot_x(0)
    , robot_y(0)  {
  (void)_alloc;
    }



   typedef uint32_t _robot_x_type;
  _robot_x_type robot_x;

   typedef uint32_t _robot_y_type;
  _robot_y_type robot_y;





  typedef boost::shared_ptr< ::robot1::board_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot1::board_<ContainerAllocator> const> ConstPtr;

}; // struct board_

typedef ::robot1::board_<std::allocator<void> > board;

typedef boost::shared_ptr< ::robot1::board > boardPtr;
typedef boost::shared_ptr< ::robot1::board const> boardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot1::board_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot1::board_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot1::board_<ContainerAllocator1> & lhs, const ::robot1::board_<ContainerAllocator2> & rhs)
{
  return lhs.robot_x == rhs.robot_x &&
    lhs.robot_y == rhs.robot_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot1::board_<ContainerAllocator1> & lhs, const ::robot1::board_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot1::board_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot1::board_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot1::board_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot1::board_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot1::board_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot1::board_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot1::board_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c388db48c5cd0fed06741e9101f00f3";
  }

  static const char* value(const ::robot1::board_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c388db48c5cd0feULL;
  static const uint64_t static_value2 = 0xd06741e9101f00f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot1::board_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot1/board";
  }

  static const char* value(const ::robot1::board_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot1::board_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 robot_x\n"
"uint32 robot_y\n"
;
  }

  static const char* value(const ::robot1::board_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot1::board_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_x);
      stream.next(m.robot_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct board_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot1::board_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot1::board_<ContainerAllocator>& v)
  {
    s << indent << "robot_x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_x);
    s << indent << "robot_y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT1_MESSAGE_BOARD_H
